-- MySQL Script generated by MySQL Workbench
-- ven. 12 janv. 2018 11:45:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gazetteer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gazetteer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pythounews`;

CREATE SCHEMA IF NOT EXISTS `pythounews` DEFAULT CHARACTER SET utf8 ;
USE `pythounews` ;


-- -----------------------------------------------------
-- Table `pythounews`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pythounews`.`user` ;

CREATE TABLE IF NOT EXISTS `pythounews`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_nom` TINYTEXT NOT NULL,
  `user_login` VARCHAR(45) NOT NULL,
  `user_bio` MEDIUMTEXT NULL,
  `user_promo`INT(4) NULL,
  `user_spe` TEXT NULL,
  `user_email` TINYTEXT NULL,
  `user_password` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC))
ENGINE = InnoDB;


